name: Snappy-java CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    # strategy:
    #   matrix:
    #     os:
    #       - ubuntu-latest
    #       - s390x-linux-gnu

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: add permission
        run: chmod +x ./docker/dockcross-s390x
        
      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y libc6-dev-s390x-cross build-essential libgcc-11-s390x-cross gcc-11-cross-base openjdk-8-jdk libstdc++-11-dev-s390x-cross libtool 

      - name: Set variables JAVA_HOME
        run: export JAVA_HOME=//usr/lib/jvm/java-8-openjdk-s390x
      - name: Set variables PATH
        run: export PATH=$JAVA_HOME/bin:$PATH

      # - name: Run commands
      #   run: make IBM_JDK_7=1 USE_GIT=1 GIT_SNAPPY_BRANCH=1.1.9 GIT_REPO_URL=https://github.com/google/snappy.git
      # - name: Set up JDK
      #   uses: actions/setup-java@v1
      #   with:
      #     java-version: 8

      - name: Build and Test
        run: make clean linux-s390x
        env:
          OCI_EXE: docker

