name: Build Native

on:
  workflow_dispatch:

jobs:
  build:
    name: Build native libraries
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: add permission
        run: chmod +x ./docker/dockcross-s390x
      - name: Build native libraries
        run: make clean-native native-all
        env:
          OCI_EXE: docker
      - name: Upload native libraries
        uses: actions/upload-artifact@v3
        with:
          name: native-libs
          path: src/main/resources/org/xerial/snappy/native/
  push:
    name: Push new native libraries to branch
    runs-on: ubuntu-22.04
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - name: Download native libraries
        uses: actions/download-artifact@v3
        with:
          name: native-libs
          path: src/main/resources/org/xerial/snappy/native/
      - run: git status
      - name: Commit and push
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Update native libraries'
          default_author: github_actions
