name: s390x CI support

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: add permission
        run: chmod +x ./docker/dockcross-s390x
        
      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential openjdk-8-jdk libtool 

      - name: Set variables JAVA_HOME
        run: export JAVA_HOME=//usr/lib/jvm/java-8-openjdk-s390x
      - name: Set variables PATH
        run: export PATH=$JAVA_HOME/bin:$PATH

      - name: Build and Test
        run: make clean linux-s390x
        env:
          OCI_EXE: docker

